# Generated by Django 5.2.1 on 2025-05-21 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_producto_costo"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="revendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ventas_revendedor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("DISTRIBUIDOR", "Distribuidor"),
                    ("REVENDEDOR", "Revendedor"),
                ],
                default="DISTRIBUIDOR",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AsignacionRevendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "distribuidor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_revendedor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.producto"
                    ),
                ),
                (
                    "revendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_asignado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
